### ISSUE TITLE
You can highlight the ✓ in the checkbox

### ISSUE THREAD

**Issue by MartensCedric** [BinarSkugga/UsubaUI#5]
As seen here : 
![Imgur](http://i.imgur.com/wG5Q46f.png)

# [This](https://stackoverflow.com/questions/6900124/how-to-make-certain-text-not-selectable-with-css) will probably fix it

### EDIT : I'm on Firefox

**Comment by PierreOlivierBrillant** [comment]
Same thing on Edge. Chrome seems to look fine.
![image](https://cloud.githubusercontent.com/assets/19349898/26601103/a5505a26-454c-11e7-9e4f-2bbecc42b9b1.png)

**Comment by BinarSkugga** [comment]
Will after my class, just a browser prefix problem.
